# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'DcoXz5fRtkKQA9Li4jeG0Efc3'
  twitter_api_secret: 'iYTC5SbLweG8arMjJoTiPgdFepObUst8RHCWM2HDXOJPLBldt5'

development:
  secret_key_base: dd479552e5db62c009c2f12316afddf469f417f4a20f0d3c3a8c4ccd4672bc94b61ecb3f2754cdd283b44bcec21b779bb25b83aa54f59a751ba612a779c45a47
  <<: *default_twitter

test:
  secret_key_base: b378cbf2d6d8cdb1404090ea16bdf91ffa12789d1190e1c64d6ba05f7fd56e60b0edb3195de97b3c273934707738e66607d8ee6eecf5000f5fc22e48311f7914
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: dd479552e5db62c009c2f12316afddf469f417f4a20f0d3c3a8c4ccd4672bc94b61ecb3f2754cdd283b44bcec21b779bb25b83aa54f59a751ba612a779c45a47
  <<: *default_twitter

staging:
  secret_key_base: dd479552e5db62c009c2f12316afddf469f417f4a20f0d3c3a8c4ccd4672bc94b61ecb3f2754cdd283b44bcec21b779bb25b83aa54f59a751ba612a779c45a47
  <<: *default_twitter
